env:
  name: keypointMaxObsTask
  num_envs: 2048
  spacing: 4

  humanoid_asset_filename:  # from the project root
    assets/urdf/amp_humanoid.xml
  joint_information_path:
    assets/urdf/joint_information.yaml

  num_states: 1  # do not use
  num_obs: 223  # naive humanoid (max observation)
  num_act: 28  # dof(#) - naive humanoid
  max_episode_steps: 1200

  stiffness_coef: 1.0
  damping_coef: 1.0

  recovery_limit: 60
  drop_on_reset_prob: 0
  reference_state_init_prob: 0.5
  viewer_follow_env0: False

sim:
  headless: True
  device_id: 0
  engine: PHYSX
  num_sub_steps: 2
