env:
  name: keypointTask
  num_envs: 4096
  spacing: 4

  humanoid_asset_filename:  # from the project root
    assets/urdf/amp_humanoid.xml
  num_obs: 125
  num_states: 1  # do not use
  num_act: 28  # number of dof
  max_episode_steps: 1200


sim:
  headless: True
  device_id: 0
  engine: PHYSX
