env:
  name: locationTask
  num_envs: 50
  spacing: 4

  humanoid_asset_filename:  # from the project root
    assets/urdf/amp_humanoid_sword_shield.xml
#    assets/urdf/amp_humanoid.xml
  joint_information_path:
    assets/urdf/joint_information.yaml

  num_states: 1  # do not use
  num_obs: 253  # sword and shield (max observation)
#  num_obs: 223  # naive humanoid (max observation)
  num_act: 31  # dof(#) - sword and shield
#  num_act: 28  # dof(#) - naive humanoid
  max_episode_steps: 1200

  recovery_limit: 0
  drop_on_reset_prob: 0
  reference_state_init_prob: 1.0
  viewer_follow_env0: False

  task:
    away_max: 5.0
    away_min: 0.5
    update_freq_max: 500
    update_freq_min: 150

    asset_filename:
      assets/urdf/location_marker.urdf

sim:
  headless: False
  device_id: 0
  engine: PHYSX
