test: False

algo:
  name: rlAlgo
  memo: removed_height_reward

model:
  name: core

network:
  name: core
  separate: True

  space:
    continuous:
      mu_activation: None
      sigma_activation: None
      mu_init:
        name: default
      sigma_init:
        name: const_initializer
        val: 3.0
      fixed_sigma: True

  mlp:
    units: [1024, 512]
    activation: relu
    initializer:
      name: default


checkpoint:  # from the project root
  runs/rlTask_rlAlgo_22-18-46-34_removed_height_reward/nn/rlTask.pth


hparam:
  normalize_input: True
  normalize_value: True
  normalize_advantage: True
  clip_value: False
  reward_shaper: {}
  save_frequency: 200

  # learning hyperparameters
  horizon_length: 32
  gamma: 0.99
  tau: 0.95
  e_clip: 0.2
  grad_norm: 1.0

  minibatch_size: 1024
  mini_epochs: 6

  learning_rate: 5e-4
  lr_schedule: adaptive
  kl_threshold: 0.008

  bound_loss_type: regularisation
  bounds_loss_coef: 0.00001
  critic_coef: 5
  entropy_coef: 0.0

seed: 1
