test: False
debug: False

algo:
  name: skillAlgo
  memo:
  motion_file:
#    assets/motions/dataset_humanoid.yaml
#    assets/motions/amp_humanoid_run.npy
    assets/motions/reallusion_sword_shield/locomotion_and_drop_recovery.yaml
#    assets/motions/reallusion_sword_shield/locomotion2.yaml

model:
  name: skill

network:
  name: skill
  separate: True

  space:
    latent_dim: 64
#    latent_dim: 32

    continuous:
      mu_activation: None
      sigma_activation: None
      mu_init:
        name: default
      sigma_init:
        name: const_initializer
        val: -2.9
      fixed_sigma: True
      learn_sigma: False

  mlp:
    units: [1024, 1024, 512]
    activation: relu
    initializer:
      name: default

  latent:
    build: True
    units: [512, 256]

  disc:  # discriminator and encoder shares the network
    units: [1024, 1024, 512]
    activation: relu
    initializer:
      name: default

  enc:
    units: [1024, 512]
    activation: relu
    separate: True

    initializer:
      name: default

checkpoint:  # from the project root
#  runs/keypointMaxObsTask_skillAlgo_24-23-10-54_enc_loss/nn/last_keypointMaxObsTask_ep_5000_rew_-60.58973.pth

  runs/ep_17500_rew_7094.7534_17500.pth

checkpoint_disc:
#  runs/style_sword_loco_last_keypointMaxObsTask_ep_83200_rew_7216.8003.pth

hparam:
#  max_frames: 1500

  normalize_input: True
  normalize_value: True
  normalize_advantage: True
  clip_value: False
  reward_shaper: {}
  save_frequency: 1000
  intermediate_save_frequency: 100

  logger:
    motion_match_length: 4
    show_matcher_out: False
    action: False
    motion: False
    latent_motion_id: False
    motion_transition: False
    jitter: True
    filename:
      plot
#      junk

  # learning hyperparameters
  horizon_length: 32
  gamma: 0.99
  tau: 0.95
  e_clip: 0.2
  grad_norm: 1.0

  minibatch_size: 20000
  mini_epochs: 6

  learning_rate: 2e-5
  lr_schedule: constant
  bound_loss_type: bound
  bounds_loss_coef: 10
  critic_coef: 5
  entropy_coef: 0.0

  reward:
    task_weight: 0.0
    disc_weight: 0.5
    enc_weight: 0.5
    task_scale: 0.0
    disc_scale: 4.0
    enc_scale: 1.0
    show_on_player: False

  style:
    replay_buf:
      size: 100000
      store_prob: 0.01
      num_demo_update: 128

    disc:
      input_divisor: 16
      num_obs: 140
#      num_obs: 125
      obs_traj_len: 10
#      obs_traj_len: 4
      loss_coef: 5
      logit_reg_scale: 0.01
      reg_scale: 0.0001
      grad_penalty_scale: 5
      log_hist: False

  skill:
    div_loss_coef: 0.01
    enc:
      loss_coef: 5

    latent:
      update_freq_max: 150
      update_freq_min: 1

#  jitter:
#    loss_coef: 0.02
#    input_divisor: 16

seed: 1
