test: False
debug: False

algo:
  name: skillAlgo
  memo: sword_grad_penalty_20
  motion_file:
#    assets/motions/dataset_humanoid.yaml
#    assets/motions/amp_humanoid_run.npy
    assets/motions/reallusion_sword_shield/locomotion_and_drop_recovery.yaml

model:
  name: skill

network:
  name: skill
  separate: True

  space:
    latent_dim: 64
#    latent_dim: 32

    continuous:
      mu_activation: None
      sigma_activation: None
      mu_init:
        name: default
      sigma_init:
        name: const_initializer
        val: -2.9
      fixed_sigma: True

  mlp:
    units: [1024, 1024, 512]
    activation: relu
    initializer:
      name: default

  disc:  # discriminator and encoder shares the network
    units: [1024, 1024, 512]
    activation: relu
    initializer:
      name: default


checkpoint:  # from the project root
#  runs/keypointMaxObsTask_skillAlgo_11-22-32-37_humanoid_walk_latent64/nn/last_keypointMaxObsTask_ep_22800_rew_7192.233.pth
  runs/keypointMaxObsTask_skillAlgo_21-23-12-05_sword_grad_penalty_20/nn/last_keypointMaxObsTask_ep_8600_rew_7009.3784.pth

hparam:
#  max_frames: 1500

  normalize_input: True
  normalize_value: True
  normalize_advantage: True
  clip_value: False
  reward_shaper: {}
  save_frequency: 100

  logger:
    show_matcher_out: False
    action: False
    latent_motion_id: False
    motion_transition: True

    motion_match_length: 4
    filename:
      plot
#      junk

  # learning hyperparameters
  horizon_length: 32
  gamma: 0.99
  tau: 0.95
  e_clip: 0.2
  grad_norm: 1.0

  minibatch_size: 8192
  mini_epochs: 6

  learning_rate: 2e-5
  lr_schedule: constant
  bound_loss_type: bound
  bounds_loss_coef: 10
  critic_coef: 5
  entropy_coef: 0.0

  reward:
    task_scale: 0.0
    disc_scale: 2.0
    enc_scale: 0.5

    show_on_player: False

  style:
    replay_buf:
      size: 200000
      store_prob: 0.01
      num_demo_update: 128

    disc:
      input_divisor: 16
      num_obs: 140
#      num_obs: 125
      obs_traj_len: 10
#      obs_traj_len: 16
      loss_coef: 5
      logit_reg_scale: 0.01
      reg_scale: 0.0001
      grad_penalty_scale: 20
      log_hist: False

  skill:
    div_loss_coef: 0.01
    enc:
      loss_coef: 5

    latent:
      update_freq_max: 150
      update_freq_min: 1

seed: 1
