test: False
debug: False

algo:
  name: skillAlgo
  memo: drop
  motion_file:
    assets/motions/reallusion_sword_shield/dataset_reallusion_sword_shield.yaml

model:
  name: skill

network:
  name: skill
  separate: True

  space:
    latent_dim: 64

    continuous:
      mu_activation: None
      sigma_activation: None
      mu_init:
        name: default
      sigma_init:
        name: const_initializer
        val: -2.9
      fixed_sigma: True

  mlp:
    units: [1024, 1024, 512]
    activation: relu
    initializer:
      name: default

  disc:  # discriminator and encoder shares the network
    units: [1024, 1024, 512]
    activation: relu
    initializer:
      name: default


checkpoint:  # from the project root
  runs/keypointTask_skillAlgo_28-18-55-14_None/nn/keypointTask.pth


hparam:
  normalize_input: True
  normalize_value: True
  normalize_advantage: True
  clip_value: False
  reward_shaper: {}
  save_frequency: 200

  # learning hyperparameters
  horizon_length: 32
  gamma: 0.99
  tau: 0.95
  e_clip: 0.2
  grad_norm: 1.0

  minibatch_size: 16384
  mini_epochs: 6

  learning_rate: 2e-5
  lr_schedule: constant
  bound_loss_type: bound
  bounds_loss_coef: 10
  critic_coef: 5
  entropy_coef: 0.0

  reward:
    task_scale: 0.0
    disc_scale: 2.0
    enc_scale: 2.0

  style:
    replay_buf:
      size: 200000
      store_prob: 0.01

    disc:
      num_obs: 140
      obs_traj_len: 4
      loss_coef: 5
      logit_reg_scale: 0.01
      reg_scale: 0.0001
      grad_penalty_scale: 5

  skill:
    div_loss_coef: 0.01
    enc:
      loss_coef: 5

    latent:
      update_freq_max: 150
      update_freq_min: 1

seed: 1
