test: False

algo:
  name: styleAlgo
  memo: prevent_disc_learn
  style:
    motion_file: assets/motions/amp_humanoid_walk.npy
    joint_information_path: assets/urdf/joint_information.yaml

model:
  name: style

network:
  name: style
  separate: True

  space:
    continuous:
      mu_activation: None
      sigma_activation: None
      mu_init:
        name: default
      sigma_init:
        name: const_initializer
        val: -2.9
      fixed_sigma: True

  mlp:
    units: [1024, 512]
    activation: relu
    initializer:
      name: default

  disc:
    units: [1024, 512]
    activation: relu
    initializer:
      name: default


checkpoint:  # from the project root
  runs/keypointTask_styleAlgo_24-11-22-27_prevent_disc_learn/nn/keypointTask.pth
checkpoint_disc:  # from the project root
#  runs/keypointTask_styleAlgo_24-00-11-15_max_actor/nn/keypointTask.pth


hparam:
  normalize_input: True
  normalize_value: True
  normalize_advantage: True
  clip_value: False
  reward_shaper: {}
  save_frequency: 200

  # learning hyperparameters
  horizon_length: 32
  gamma: 0.99
  tau: 0.95
  e_clip: 0.2
  grad_norm: 1.0

  minibatch_size: 16384
  mini_epochs: 6

  learning_rate: 5e-4
  lr_schedule: adaptive
  kl_threshold: 0.008

#  bound_loss_type: regularisation
#  bounds_loss_coef: 0.00001
  bound_loss_type: bound
  bounds_loss_coef: 10
  critic_coef: 5
  entropy_coef: 0.0

  # style
  style:
    task_rew_scale: 0.0
    disc_rew_scale: 1.0
    replay_buf:
      size: 200000
      store_prob: 0.01

    disc:
      num_obs: 125
      obs_traj_len: 4
      loss_coef: 0.0
      logit_reg_scale: 0.01
      reg_scale: 0.0001
      grad_penalty_scale: 5

seed: 1
